### ISSUE TITLE
Doc order when saved/loaded

### ISSUE THREAD

**Issue by LoganAC34** [adrian-green/PDFSessions#3]
I already posted this issue in [NeoNavras's fork](https://github.com/NeoNavras/PDFSessions/issues/2), but he thought I should also post it here.

It would be nice if the session would save the order the documents are in the tab order - currently it seems the order is random or maybe alphabetical. Not sure if it did this in the past, but it doesn't do it now.

I'm on the 64bit version of adobe if it matters.

Thanks.

**Comment by adrian-green** [comment]
Thanks for the suggestion. 

I agree it would be good to have, however there really seems to be no way to query the app about any current custom ordering of tabs. It is worth remembering that the app can be configured to open each PDF in a separate window. Internally the tab ordering may just be a convenience for the current session, and therefore not exposed to the API.

It is possible to reorder the JSON elements using the Edit Session Data dialog - that will permanently set the load ordering.  Some inventive coding could result in some kind of UI to drag drop the ordering of the loaded PDFs around and have that reflected in the session JSON. A lot of work, hindered by the ancient version of JS used.

It is possible to create a "IAC" app to replicate the job of this tool - I believe you can set document `tabIndex` and get `numTabs` properties that way. (You'd need to create a version for each platform of course.) I can't see that happening any time soon :-)

**Comment by LoganAC34** [comment]
Well that's a bummer... Editing the JSON is how i've been doing it so far, but it's really tedious when you have a bunch of PDFs. I don't know how to do any of that so I guess i'll just have to do without it. Thanks for looking into it.

**Comment by adrian-green** [comment]
Check out https://jsoneditoronline.org/ - it allows you to drag drop JSON nodes around. It's not hugely intuitive, but once you get the hang of how the UI works, the ordering can be done fairly quickly. 

github: https://github.com/josdejong/svelte-jsoneditor

**Comment by LoganAC34** [comment]
Cool. I didn't know about this, I'll take a look. Thanks.
